/*$(document).ready(function(){
  $('.more_info').click(function(){
    $('.block_info').addClass('active_block')
    $('.more_info').hide()
      })
  $('.link_info').click(function(){
    $('.block_info').removeClass('active_block')
    $('.more_info').show()
    })
})*/
